# -*- coding: utf-8 -*-
"""RiskGuard Leon 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_WWsrpKnwdkSkH4WJXtU4xmtZXVgfvP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- PREPARACIÓN DE DATOS ---
n_poblacion = 1000000
mediana_nominal = 9460
mu, sigma = np.log(mediana_nominal), 0.5
ingresos = np.random.lognormal(mu, sigma, n_poblacion)
df = pd.DataFrame({'ingreso_nominal': ingresos})
df = df[df['ingreso_nominal'] >= 4800].copy()
df['ingreso_total'] = np.where(df['ingreso_nominal'] < 9500, df['ingreso_nominal'] * 1.12, df['ingreso_nominal'])

# --- GRÁFICA 1: DISTRIBUCIÓN DE POBLACIÓN ---
plt.figure(figsize=(10, 6))
sns.histplot(df['ingreso_total'], bins=80, color='skyblue', kde=True, edgecolor='black', alpha=0.7)
mediana_real = df['ingreso_total'].median()

plt.axvline(mediana_real, color='red', linestyle='--', linewidth=2,
            label=f'Mediana Integral: ${mediana_real:,.0f}')

plt.title('Distribución del Ingreso Integral en León', fontsize=14, pad=15)
plt.xlabel('Ingreso Mensual Total ($ MXN)', fontsize=12)
plt.ylabel('Frecuencia (Número de Socios)', fontsize=12)
plt.xlim(4000, 35000) # Enfocado en el grueso de la población
plt.legend(fontsize=12)
plt.grid(axis='y', alpha=0.3)
plt.show()

# --- CÁLCULOS DE ESTRÉS ---
canasta_ajustada = 4877.87 * (1 + (0.0062 * 2))
df['cuota_credito'] = df['ingreso_total'] * 0.40
df['excedente'] = df['ingreso_total'] - canasta_ajustada - df['cuota_credito']
df['estatus'] = np.where(df['excedente'] < 0, 'Mora Técnica',
                         np.where(df['excedente'] < 1000, 'Riesgo Crítico', 'Sano'))

# --- GRÁFICA 2: ESTATUS FINAL DE CARTERA ---
plt.figure(figsize=(9, 6))
estatus_pct = df['estatus'].value_counts(normalize=True) * 100
estatus_pct = estatus_pct.reindex(['Sano', 'Riesgo Crítico', 'Mora Técnica'])

colores_semaforo = ['#27ae60', '#f1c40f', '#c0392b']
bars = plt.bar(estatus_pct.index, estatus_pct.values, color=colores_semaforo, edgecolor='black', width=0.6)

# Añadir etiquetas de porcentaje
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 1, f'{yval:.1f}%',
             ha='center', va='bottom', fontweight='bold', fontsize=12)

plt.title('Impacto de Estrés Inflacionario en la Cartera (Marzo 2026)', fontsize=14, pad=20)
plt.ylabel('Porcentaje de la Muestra (%)', fontsize=12)
plt.ylim(0, 100)
plt.grid(axis='y', linestyle=':', alpha=0.6)
plt.show()

# --- GRÁFICA 3: DEFAULT POR DECIL ---
plt.figure(figsize=(10, 6))
df['decil'] = pd.qcut(df['ingreso_total'], 10, labels=False)
pd_decil = df[df['estatus'] == 'Mora Técnica'].groupby('decil').size() / df.groupby('decil').size() * 100
pd_decil = pd_decil.fillna(0)

# Paleta de degradado rojo para enfatizar el riesgo
bars_decil = plt.bar(pd_decil.index, pd_decil.values, color=sns.color_palette("Reds", 10), edgecolor='black')

# Etiquetas de valor
for bar in bars_decil:
    yval = bar.get_height()
    if yval > 0:
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.5, f'{yval:.1f}%',
                 ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.title('Probabilidad de Default por Decil de Ingresos (DTI 40%)', fontsize=14, pad=15)
plt.xlabel('Deciles de Ingreso (0 = Más bajos | 9 = Más altos)', fontsize=12)
plt.ylabel('% de Socios en Insolvencia Matemática', fontsize=12)
plt.xticks(range(10))
plt.grid(axis='y', alpha=0.2)
plt.show()